pipeline:
  build:
    image: saccade_dynamic
    commands:
      - mkdir build
      - cd build
      - cmake .. -DCUDA_ENABLED=OFF
      - make
  deploy:
    image: saccade_static
    commands:
      - .deploy/pipeline.sh
      - dir
    when:
      branch: master
  publish:
    image: saccade_publish
    commands:
      - /opt/publish.sh
    when:
      branch: master
