pipeline:
  build:
    image: patwie/saccade
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - make
  deploy:
    image: qt59static
    commands:
      - .deploy/pipeline.sh
      - dir
  publish:
    github_release:
      secrets: [github_token]
      files:
        - saccade_release.tar.gz
     checksum:
        - md5
        - sha1
        - sha256
        - sha512
        - adler32
        - crc32
