pipeline:
  build:
    image: patwie/saccade
    pull: true
    commands:
      - mkdir build
      - cd build
      - cmake ..
      - make
  deploy:
    image: qt59static
    pull: true
    commands:
      - .deploy/pipeline.sh
      - dir
  github_release:
    image: plugins/github-release
    secrets: [github_token]
    files:
      - saccade_release.tar.gz
   checksum:
      - md5
      - sha1
      - sha256
      - sha512
      - adler32
      - crc32
