pipeline:
  build:
    image: patwie/saccade
    commands:
      - mkdir build
      - cd build
      - cmake .. -DCUDA_ENABLED=OFF
      - make
  deploy:
    image: patwie/saccade-static
    commands:
      - .deploy/pipeline.sh
      - dir
    when:
      branch: master
  publish:
    image: publish_file
    commands:
      - /opt/publish.sh
    when:
      branch: master
